### ISSUE TITLE
react-native-fs permission error on tvOS /ioS: ENSCOCOAERRORDOMAIN513

### ISSUE THREAD

**Issue by jvjijith** [birdofpreyru/react-native-fs#59] opened 2024-08-13 14:42 UTC
I'm developing a React Native app for tvOS and encountering a file system permission error when trying to save data in json file using react-native-fs. The idea is to get the data from API and save it to a JSON file. The app works fine in the simulator, but when distributed through TestFlight and run on a real tvOS device, I get the following error: Error saving playlists to file: Error: You don't have permission to save the file "playlist" in the folder "testFolder". Error code: ENSCOCOAERRORDOMAIN513

```
const APP_FOLDER_NAME = 'testFolder';
const APP_FOLDER = DocumentDirectoryPath +`/${APP_FOLDER_NAME}`;
const PLAYLIST_FOLDER = APP_FOLDER + '/playlist';
const PLAYLIST_FILE = PLAYLIST_FOLDER + '/playlist.json';
const savePlaylistsToFile = async (data) => {
try {
const folderExists = await exists(PLAYLIST_FOLDER);
if (!folderExists) {
await mkdir(PLAYLIST_FOLDER);
console.log('Playlist folder created');
}
await writeFile(PLAYLIST_FILE, JSON.stringify(data), 'utf8');
console.log('Playlists saved to file');
} catch (err) {
console.error('Error saving playlists to file:', err.message, 'Code:', err.code);
}
};

```
The app works as expected in the simulator, but fails only on the TestFlight build on a real tvOS device. 
The issue also happens when running app directly on tv using xCode.

Questions:

What could be causing this permission error specifically in the real device environment? Are there any tvOS-specific considerations for file system access that I'm missing?

Struggling with this issue for couple of days now.

**Comment by birdofpreyru** [comment] 2024-08-13 17:51
I don't know &mdash; I don't have any experience with tvOS, I don't have a real tvOS device to test with, and in general supporting tvOS is beyond my interests & capacity at the moment.

**Comment by birdofpreyru** [comment] 2024-08-13 23:51
Agh, might be caused by security scopes? See [pickFile()](https://github.com/birdofpreyru/react-native-fs/tree/master?tab=readme-ov-file#pickfile) &msdash; that’s the way to access files on iOS / macOS in locations which can’t be read otherwise. Perhaps you need something similar to write to the location you want on tvOS.

**Comment by jvjijith** [comment] 2024-08-16 17:42
The issue is that in tvos DocumentDirectoryPath is restricted , you need to use CacheDirectory to save files.

**Comment by birdofpreyru** [comment] 2024-08-16 17:49
Ok, does it mean, we can close this issue?

**Comment by jvjijith** [comment] 2024-08-16 17:55
yes you can close this issue

**Closed** 2024-08-16 17:55 UTC
Labels: P2, On Hold, tvOS
