### ISSUE TITLE
[Windows] `readDir()` `.isFile()` and `.isDirectory()` don't resolve correctly

### ISSUE THREAD

**Issue by AchillesChristianPrinz** [birdofpreyru/react-native-fs#81] opened 2024-11-10 00:40 UTC
In the `readDir` method the resulting callbacks `isFile()` and `isDirectory()` compare the wrong types.
On the JS side you assume that `file.type` is a string when comparing it to any of those values: `const { FileTypeDirectory, FileTypeRegular } = RNFS.getConstants()`
https://github.com/birdofpreyru/react-native-fs/blob/5df8019b05bdc02ea678c0b569c4526518137aa9/src/index.ts#L64
https://github.com/birdofpreyru/react-native-fs/blob/5df8019b05bdc02ea678c0b569c4526518137aa9/src/index.ts#L65

But at least on react-native-windows and probably also on android the type of `file.type` is a `number`.  This results in both callbacks always resolving to false wheter it is a file or a directory.

Here are the assignments on the native side:
https://github.com/birdofpreyru/react-native-fs/blob/5df8019b05bdc02ea678c0b569c4526518137aa9/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsModule.kt#L529
https://github.com/birdofpreyru/react-native-fs/blob/5df8019b05bdc02ea678c0b569c4526518137aa9/windows/ReactNativeFs/ReactNativeModule.cpp#L511

My temporary solution (just tested on rn-windows) is to cast the type to a String:
```ts
isFile: () => String(file.type) === FileTypeRegular,
isDirectory: () => String(file.type) === FileTypeDirectory
```
But the whole thing should probably be deprecated and the `type: 'file' | 'directory'` be passed through from the native side, instead of using two callbacks to resolve a possible number or string to a boolean

**Comment by birdofpreyru** [comment] 2024-11-10 12:05
Thanks @AchillesChristianPrinz !

Looking at [the `readDir()` test in Example App](https://github.com/birdofpreyru/react-native-fs/blob/5df8019b05bdc02ea678c0b569c4526518137aa9/example/src/TestBaseMethods.tsx#L672-L764), where `isDirectory()` and `isFile()` checks are disabled for Windows, I believe it was broken on Windows only. I see, on Android the implementation violates the typing at TypeScript side, but works correctly in the runtime, because both the field, and the corresponding constants are assigned numeric values rather than strings.

> _But the whole thing should probably be deprecated and the type: 'file' | 'directory' be passed through from the native side, instead of using two callbacks to resolve a possible number or string to a boolean_

I agree. The current goofy design is inherited from the original upstream code. I thought about this exact change, among other stuff, for v3 of the library (to keep the current v2 as close to the drop-in replacement of the original library, as possible); but v3 is unlikely to happen any time soon.

So, for now the fix will be to ensure correct string values are assigned to related fields and constants on the native side on Windows and Android; I'll do it when updating Windows version to RN@0.76 (which is still on hold, because #76).

**Comment by AchillesChristianPrinz** [comment] 2024-11-10 19:11
Thanks for your quick response. This won't probably last long since the are already @ preview5 or so.

**Comment by alessandro-bottamedi** [comment] 2024-11-13 09:39
I have the same problem on iOS (RN 0.76.1), isFile and isDirectory resolve always "false".

**Comment by birdofpreyru** [comment] 2024-11-13 09:44
@alessandro-bottamedi it might be different. On iOS there are more resource types, beyond directory and regular file: https://developer.apple.com/documentation/foundation/nsurlfileresourcetype. As of now (the same as in the original upstream), `isFile()` evaluates _true_ just for `NSURLFileResourceTypeRegular`, and `isDirectory()` evals _true_ just for `NSURLFileResourceTypeDirectory`.

**Comment by alessandro-bottamedi** [comment] 2024-11-13 10:49
> @alessandro-bottamedi it might be different. On iOS there are more resource types, beyond directory and regular file: https://developer.apple.com/documentation/foundation/nsurlfileresourcetype. As of now (the same as in the original upstream), `isFile()` evaluates _true_ just for `NSURLFileResourceTypeRegular`, and `isDirectory()` evals _true_ just for `NSURLFileResourceTypeDirectory`.

But with RN 0.75 and version 2.28 of the package, isFile and isDirectory respond correctly with the same files…

**Comment by birdofpreyru** [comment] 2024-11-15 23:03
**Update**: It turns out, making this library and its Example App to work with RN@0.76 (New Arch) on Windows is an undertaking too large for me, unless it is sponsored by somebody (https://github.com/birdofpreyru/react-native-fs/issues/76#issuecomment-2480072076). For similar reasons I can't support multiple versions of RN / fix something in older versions of the library. Thus, the Windows part of the issue will be put _On Hold_ indefinitely.

At the same time, I found & fixed the issue for iOS / macOS (it turned out to be a regression introduced when implementing support of security-scoped URLs). I'll probably release it over the weekend, or the next week, once complete some more fixes related to special characters support in path names (#82, #85) on Android / iOS / macOS.

**Comment by pcprinz** [comment] 2024-11-16 08:55
Maybe I'll take the time to make a PR for the tasks on the windows side, once you released the changes. I just have to figure out how to build and test the project.

But the other way around, I can build and test Windows and Android only, so if I have to make changes on the js side you'll probably have to make regression tests for iOS/MacOS.

**Comment by birdofpreyru** [comment] 2024-11-16 10:53
> _how to build and test the project._

Yeah... that's the crux of the problem &mdash; Example App depends on `react-native-static-server`, and that, with its own Example App, depends both on `react-native-fs` and `react-native-webview`; to make everything build with RN@0.76 / New Arch on Windows, it requires upgrading all three libs at the same time, and `react-native-webview` in particular is a problem, as it isn't well aligned with the template code created by `react-native-windows`, thus I can't easily upgrade that without digging into implementation details.

> _if I have to make changes on the js side_

I believe, the fix here should be on native side &mdash; just correcting the values assigned to related fields and constants to ensure they are all strings. Quite simple, but a pain to test without being able to build Example App.

**Comment by pcprinz** [comment] 2024-11-23 01:13
> I believe, the fix here should be on native side — just correcting the values assigned to related fields and constants to ensure they are all strings. Quite simple, but a pain to test without being able to build Example App.

You're totally right - This is all on the native side. I already got this patched in my app.

I got the example app running on windows, but only 10/25 tests passed. 2 of the failing were missing an `await`. Me and the copilot are currently into a refactoring of the tests. I'll try to get everything passed for windows. Afterwards It would be nice if you could run the tests for the other platform to ensure everything's still fine. 

When this is done I'll fix the "Umlauts" and `isDirectory` / `isFile` issues, as well as the "new NativeEmitter" warning on windows. 

> ... to make everything build with RN@0.76 / New Arch on Windows ...

I'm doing this on the uwp Version 0.76 that you installed for the example app. As it seems it's still possible to do it "the old way".
Imo It's better to get the issues done before upgrading than just waiting for the dependency-deadlock to disappear - has to be done anyways.

Maybe there has to be a way for the example app to release the dependency on `react-native-static-server` - would make things way easier.

**Closed** 2024-11-29 18:04 UTC
Labels: P1, Ready, Windows
