### ISSUE TITLE
Build not passing the "commonly found issues" check on Google Play Console

### ISSUE THREAD

**Issue by AdamGerthel** [birdofpreyru/react-native-fs#92] opened 2024-12-13 23:51 UTC
I just replaced react-native-fs with this package in order to get new arch support and I'm getting the following error mesage from Google Play: 

> Kotlin incompatibilities will cause crashes
Your app uses Kotlin's removeFirst() and removeLast() extension functions, which conflict with Java functions in Android 15. This will cause apps to crash on devices on Android 14 or earlier. Your app uses these functions in the following places:
com.drpogodin.reactnativefs.ReactNativeFsModule.copyFileAssets
To avoid crashes, we recommend replacing any Kotlin removeFirst() and removeLast() function calls with removeAt(0) and removeAt(list.lastIndex).

I couldn't find any issues about this. Any idea how to solve it?

**Comment by alessandro-bottamedi** [comment] 2024-12-14 20:13
Same for me... for now you can continue and ignore the error...

**Comment by AdamGerthel** [comment] 2024-12-15 14:37
I did that because I'm only using this package for a very small and niche use-case, but I suspect that if/when that function is called, it will crash on some devices.

**Comment by birdofpreyru** [comment] 2024-12-15 17:18
Hey @AdamGerthel, do you face it with the latest library version? The issue, indeed, used to be around for some time; however, I've noticed and fixed it back in [v2.29.1](https://github.com/birdofpreyru/react-native-fs/releases/tag/v2.29.1). Related code now reads:
https://github.com/birdofpreyru/react-native-fs/blob/036d76bb500b4bfb0ca1e478223593632be92889/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsModule.kt#L176-L177
which is fine as per Android Studio: SDKs >= 35 are supposed to support `.removeLast()`, while for older SDKs it falls back for older alternative. I wonder, whether Google.Play's code analysis is subpar to the Android Studio, leading to a false positive, or am I missing something here?

**Comment by AdamGerthel** [comment] 2024-12-15 17:25
Yes, I'm on 2.30.1. Have not used any older versions as this was the first time I used this fork.

**Comment by birdofpreyru** [comment] 2024-12-15 17:40
Ok. I believe, it should work as is just fine on all Android versions, despite the warning. I'll keep the ticket open for sometime, just as a reminder to additionally have an eye on it.

**Comment by AdamGerthel** [comment] 2024-12-15 18:23
Ok, thanks. Good to know!

**Comment by cixio** [comment] 2024-12-15 20:51
same here, fixed by ignoring it

**Comment by birdofpreyru** [comment] 2024-12-26 22:45
**Update:** After publishing an update of my Android app, for the first time since you reported this issue, and seeing how this Google.Play check annoyingly interrupts the publishing attempt until explicitly confirmed to proceed, I'll sure will remove the code line triggering that warning in the next library version.

**Comment by AdamGerthel** [comment] 2024-12-26 22:50
> **Update:** After publishing an update of my Android app, for the first time since you reported this issue, and seeing how this Google.Play check annoyingly interrupts the publishing attempt until explicitly confirmed to proceed, I'll sure will remove the code line triggering that warning in the next library version.

Yeah, sometimes you need to wait up to 15 minutes before it finds the issue and aborts the submission 😖

**Closed** 2024-12-27 11:16 UTC
Labels: P1, Ready
